server:
    port: 8080
    
logging:
    level:
        ROOT: INFO
        com.mongo.blog: INFO
        io.github.jhipster: INFO

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    data:
        mongodb:
            database: heroku_lbdpdmb0      
   
    thymeleaf:
        cache: true

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

jhipster:
    http:
        version: V_1_1
        cache: 
            timeToLiveInDays: 1461
    security:
        remember-me:            
            key: 965f1e8fc37752b23e15a12a49a316bba84e2387380628280325450fc2121dbadea3513d996c3c41e9989e52e56f411c0017



