server:
    port: 8080
    
logging:
    level:
        ROOT: INFO
        com.mongo.blog: INFO
        io.github.jhipster: INFO

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    data:
        mongodb:
            database: heroku_lbdpdmb0
            
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024


jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    security:
        remember-me:
            # security key (this key should be unique for your application, and kept secret)
            key: 965f1e8fc37752b23e15a12a49a316bba84e2387380628280325450fc2121dbadea3513d996c3c41e9989e52e56f411c0017
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: blogmongo@localhost
        base-url: http://my-server-url-to-change # Modify according to your server's URL
    metrics:
        logs: # Reports metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

